### ISSUE TITLE
Onload doesn't work

### ISSUE THREAD

**Issue by Allen-B1** [JRProgramming/BB-Planner#4]
JRProgramming said:
> So, I want it to load the 6 notes when it opens
> So far it does nothing

**Comment by JRProgramming** [comment]
I'll remove the onload right now, and make a PR on what you think the solution is.

**Comment by Allen-B1** [comment]
OK

**Comment by Allen-B1** [comment]
What did you change?

**Comment by JRProgramming** [comment]
I fixed something in the index.html that was supposed to do the function when the website opens

**Comment by Allen-B1** [comment]
The FAB doesn't work anymore

**Comment by JRProgramming** [comment]
What's the FAB

**Comment by Allen-B1** [comment]
The floating action button

**Comment by Allen-B1** [comment]
https://material.io/guidelines/components/buttons-floating-action-button.html

**Comment by JRProgramming** [comment]
Not supposed to work

**Comment by Allen-B1** [comment]
Then just remove it

**Comment by JRProgramming** [comment]
Don't want to work

**Comment by JRProgramming** [comment]
Will get rid of it soon

**Comment by JRProgramming** [comment]
Or now

**Comment by Allen-B1** [comment]
Ok, so you want to automatically load?

**Comment by JRProgramming** [comment]
Yes

**Comment by Allen-B1** [comment]
Try this:

```js
window.onload = function() {
  for(var i = 0; i < /*number of classes*/; i++) {
    addAndSaveNote();
  }
}
```

replace `/* number of classes */` with the # of classes

**Comment by JRProgramming** [comment]
Okay, will

**Comment by JRProgramming** [comment]
Didn't work

**Comment by Allen-B1** [comment]
Hmmm, i made a PR

**Comment by JRProgramming** [comment]
Thanks for the PR

**Comment by Allen-B1** [comment]
No problem

**Comment by JRProgramming** [comment]
I like what you did, let me remove the alert and see what happens

**Comment by JRProgramming** [comment]
Merged

**Comment by JRProgramming** [comment]
IT WORKED!!!

**Comment by Allen-B1** [comment]
yay
