### ISSUE TITLE
Redirect to index.html

### ISSUE THREAD

**Issue by Allen-B1** [JRProgramming/BB-Planner#6]
Redirect to `index.html` and send the data to Firebase Database

**Comment by Allen-B1** [comment]
Only thing i can suggest is to add a `setTimeout` timer

**Comment by JRProgramming** [comment]
I'm trying to test out what is the problem by making the computer send alerts on certain scenarios

**Comment by JRProgramming** [comment]
Fixed it

**Comment by JRProgramming** [comment]
Didn't fix it

**Comment by JRProgramming** [comment]
The setTimeout feature sort of worked

**Comment by JRProgramming** [comment]
I created a temporary button for now because this little issue is consuming too much time for me.

**Comment by JRProgramming** [comment]
Use what I did for sign up for this.

**Comment by JRProgramming** [comment]
Fixed it, no more issues, YA!

**Comment by Allen-B1** [comment]
ok
