### ISSUE TITLE
Error alert popping up

### ISSUE THREAD

**Issue by Allen-B1** [JRProgramming/BB-Planner#8]
There was an `alert` box that said that there was a network issue but the planner worked after the alert box.

**Comment by Allen-B1** [comment]
Only happens when you sign up

**Comment by JRProgramming** [comment]
Yep, need to fix that

**Comment by Allen-B1** [comment]
And it also only happens sometimes.

**Comment by JRProgramming** [comment]
Yep

**Comment by JRProgramming** [comment]
I fixed it, let me know if it happened again and tell me what happened before it happened.
