### ISSUE TITLE
Error dialog box

### ISSUE THREAD

**Issue by Allen-B1** [JRProgramming/BB-Planner#9]
I got a dialog box
> There is no user record corresponding to this identifier. The user may have been deleted.

What does that mean?

**Comment by JRProgramming** [comment]
I'm not sure when you got that, can you tell me the scenario in which you got that dialog box?

**Comment by JRProgramming** [comment]
Oh, this happens when I delete a user from the server because I need to test something, this shouldn't happen when this site is ready.

**Comment by JRProgramming** [comment]
If you do see this, please tell me
